jwt:
  time: 828434d28
  secret: hello-world21241223
posco:
  name: 332245기
  count: 20212323
test:
  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp&characterEncoding=UTF-8
    username: root
    password: 1234
